# Generate-CMakeModuleSources.ps1
# Emits <ModuleName>Sources.cmake with an explicit file list for target_sources.
# Re-run after adding/removing sources under the scanned paths, then commit the .cmake file.
#
# Usage:
#   .\Engine\Tools\Generate-CMakeModuleSources.ps1 -ModuleRoot Engine\Source\Core\NNCore -VariableName NNCore
#   .\Engine\Tools\Generate-CMakeModuleSources.ps1 -ModuleRoot Engine\Source\Core\NNCore -VariableName NNCore -RelativeGlobs @('.Generated/*.h', 'Source/Asset/*.cpp', ...)

[CmdletBinding()]
param(
    [Parameter(Mandatory = $true)]
    [string] $ModuleRoot,

    [Parameter(Mandatory = $true)]
    [string] $VariableName,

    [string[]] $RelativeGlobs,

    [string] $OutputFile
)

$ErrorActionPreference = 'Stop'

$repoRoot = (Resolve-Path (Join-Path $PSScriptRoot '..\..')).Path
$modulePath = if ([System.IO.Path]::IsPathRooted($ModuleRoot)) { $ModuleRoot } else { Join-Path $repoRoot $ModuleRoot }
$modulePath = (Resolve-Path $modulePath).Path

$extensions = @('.cpp', '.c', '.h', '.hpp', '.inl')
$files = [System.Collections.Generic.HashSet[string]]::new([StringComparer]::OrdinalIgnoreCase)

function Add-FilesFromGlob {
    param([string] $Pattern)
    $fullPattern = Join-Path $modulePath $Pattern
    $parent = Split-Path -Parent $fullPattern
    if (-not (Test-Path -LiteralPath $parent)) {
        return
    }
    Get-ChildItem -Path $fullPattern -File -ErrorAction SilentlyContinue | ForEach-Object {
        $rel = $_.FullName.Substring($modulePath.Length).TrimStart('\', '/')
        $rel = $rel -replace '\\', '/'
        [void]$files.Add($rel)
    }
}

if (-not $RelativeGlobs -or $RelativeGlobs.Count -eq 0) {
    Write-Error "RelativeGlobs is required."
}

foreach ($glob in $RelativeGlobs) {
    Add-FilesFromGlob -Pattern $glob
}

$sorted = $files | Sort-Object

if (-not $OutputFile) {
    $OutputFile = Join-Path $modulePath "${VariableName}Sources.cmake"
} elseif (-not [System.IO.Path]::IsPathRooted($OutputFile)) {
    $OutputFile = Join-Path $modulePath $OutputFile
}

$sb = New-Object System.Text.StringBuilder
[void]$sb.AppendLine("# Generated by Engine/Tools/Generate-CMakeModuleSources.ps1 - do not edit by hand.")
[void]$sb.AppendLine("set(${VariableName}_SOURCES")
foreach ($f in $sorted) {
    $escaped = $f -replace '\\', '/'
    [void]$sb.AppendLine("    ${escaped}")
}
[void]$sb.AppendLine(")")

$content = $sb.ToString()
[System.IO.File]::WriteAllText($OutputFile, $content, [System.Text.UTF8Encoding]::new($false))
Write-Host "Wrote $($sorted.Count) files to $OutputFile"
