# Generated by Engine/Tools/Generate-CMakeModuleSources.ps1 - do not edit by hand.
set(NNRuntimeRmlui_SOURCES

    Include/Rml/RendererExtensions.h
    Include/Rml/RenderInterfaceGL3SDL.h
    Include/Rml/RmlUi_Include_Windows.h
    Include/Rml/RmlUi_Platform_SDL.h
    Include/Rml/RmlUi_Renderer_GL3.h
    Include/Rml/Shell.h
    Include/Rml/ShellFileInterface.h
    Include/ABI/RmlRendererAbi.h

    Source/Rml/RendererExtensions.cpp
    Source/Rml/RenderInterfaceGL3SDL.cpp
    Source/Rml/RmlUi_Platform_SDL.cpp
    Source/Rml/RmlUi_Renderer_GL3.cpp
    Source/Rml/Shell.cpp
    Source/Rml/ShellFileInterface.cpp
     
    Source/System/NNRmlUIModule.cpp
    Source/System/NNRmlUISystem.cpp
    Source/Renderer/RmlUIRenderer.cpp
    Source/Renderer/RmlRenderer.cpp
    Source/ABI/RmlUIRuntimeApi.cpp
    Source/ABI/RmlRendererAbi.cpp

    # Native
    Source/Native/Context.cpp

    Source/Native/Element.cpp
    Source/Native/ElementDocument.cpp
    Source/Native/ElementFormControlInput.cpp
    Source/Native/ElementCustom.cpp
    Source/Native/ElementInstancer.cpp

    Source/Native/Variant.cpp
    Source/Native/VariableDefinition.cpp
    Source/Native/StructHandle.cpp
    Source/Native/Dictionary.cpp
    Source/Native/DataVariable.cpp
    Source/Native/DataModelHandle.cpp
    Source/Native/DataModelConstructor.cpp
    Source/Native/Event.cpp
    Source/Native/EventInstancer.cpp
    Source/Native/EventListener.h
    Source/Native/EventListenerInstancer.cpp

    Source/Native/Box.cpp
    Source/Native/RenderManager.cpp

    Source/Native/RenderInterface.cpp
    Source/Native/SystemInterface.cpp
    Source/Native/FileInterface.cpp
    Source/Native/Plugin.cpp

    Source/Native/StyleSheetContainer.cpp
    Source/Native/StyleSheetSpecification.cpp
    
    Source/Native/XMLAttributes.cpp
    Source/Native/PropertyDefinition.cpp
    Source/Native/Property.cpp
    Source/Native/Rml.cpp
    Source/Native/Debugger.cpp
    Source/Native/Util.h
    Source/Native/Buffer.cpp

    Include/Native/Buffer.h
    Include/Native/Pool.h
    Include/Native/RmlNative.h
    Include/Native/StreamFile.h
)
