# Generated by Engine/Tools/Generate-CMakeModuleSources.ps1 - do not edit by hand.
set(NNRuntimeRmlui_SOURCES

    Include/Rml/RendererExtensions.h
    Include/Rml/RenderInterfaceGL3SDL.h
    Include/Rml/RmlUi_Include_Windows.h
    Include/Rml/RmlUi_Platform_SDL.h
    Include/Rml/RmlUi_Renderer_GL3.h
    Include/Rml/Shell.h
    Include/Rml/ShellFileInterface.h
    
    Source/Rml/RendererExtensions.cpp
    Source/Rml/RenderInterfaceGL3SDL.cpp
    Source/Rml/RmlUi_Platform_SDL.cpp
    Source/Rml/RmlUi_Renderer_GL3.cpp
    Source/Rml/Shell.cpp
    Source/Rml/ShellFileInterface.cpp
    
    Source/System/NNRmlUIModule.cpp
    Source/System/NNRmlUISystem.cpp
    Source/Renderer/RmlUIRenderer.cpp
)
