// ============================================================================
// AutoRegisterScriptAttribute.cs - Source Generator 注册标记
// ============================================================================
// 标记需要自动注册的脚本类型，Source Generator 会扫描此特性并生成注册代码。
// ============================================================================

namespace Neverness.Gameplay;

/// <summary>
/// 自动注册脚本特性：标记需要自动注册的脚本类型。
/// </summary>
/// <remarks>
/// ⚠️ Source Generator 会在编译时扫描此特性，并生成静态注册代码。
///
/// 使用示例：
/// <code>
/// [AutoRegisterScript]
/// public class PlayerController : EntityBehaviour
/// {
///     // ...
/// }
/// </code>
///
/// Source Generator 会生成：
/// <code>
/// public static class ScriptRegistry_AutoGenerated
/// {
///     public static void RegisterAll(ScriptRegistry registry)
///     {
///         registry.Register&lt;PlayerController&gt;();
///     }
/// }
/// </code>
/// </remarks>
[AttributeUsage(AttributeTargets.Class, Inherited = false, AllowMultiple = false)]
public sealed class AutoRegisterScriptAttribute : Attribute
{
    /// <summary>显示名称（可选）。</summary>
    public string? DisplayName { get; set; }

    /// <summary>分类标签（可选）。</summary>
    public string? Category { get; set; }

    /// <summary>是否禁用（可选）。</summary>
    public bool IsDisabled { get; set; }

    /// <summary>默认构造函数。</summary>
    public AutoRegisterScriptAttribute() { }

    /// <summary>带显示名称的构造函数。</summary>
    /// <param name="displayName">显示名称。</param>
    public AutoRegisterScriptAttribute(string displayName)
    {
        DisplayName = displayName;
    }
}
