# Generated by Engine/Tools/Generate-CMakeModuleSources.ps1 - do not edit by hand.
set(NNEditor_SOURCES
    Include/EditorInitializer.h
    Include/EngineEditor.h
    Include/RuntimeKernelEditorLoop.h
    Main.cpp
    Source/EditorInitializer.cpp
    Source/EngineEditor.cpp
    Source/RuntimeKernelEditorLoop.cpp
)
