#ifndef VFS_CONFIG_H
#define VFS_CONFIG_H

#ifndef VFS_ENABLE_MULTITHREADING
#define VFS_ENABLE_MULTITHREADING 1
#endif

#if VFS_ENABLE_MULTITHREADING
#define VFS_MT_SUPPORT_ENABLED 1
#else
#define VFS_MT_SUPPORT_ENABLED 0
#endif

#endif // VFS_CONFIG_H
